name: Bun Diff Action
description: Show diff of bun.lockb on Pull Request.

branding:
  icon: file-plus
  color: gray-dark

inputs:
  token:
    description: The GitHub token to use for creating/updating comments
    required: false
    default: ${{ github.token }}
  bun-version:
    description: |
      The version of bun to install. If not provided, the latest version will be installed.
      If already bun is installed, this input is ignored.
    required: false
  # TODO: bun-version-file

runs:
  using: node20
  main: dist/index.js
