name: Bun Diff Action
description: Show diff of bun.lockb on Pull Request.

branding:
  icon: file-plus
  color: gray-dark

inputs:
  token:
    description: The GitHub token to use for creating/updating comments
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
