name: Bun Diff
description: Create a comment with the diff of the `bun.lockb` file.

branding:
  icon: file-plus
  color: gray-dark

inputs:
  token:
    description: The GitHub token to use for creating/updating comments
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
