name: CI
run-name: CI (${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.sha }})

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun run lint

  run-action:
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to comment on the commit
      pull-requests: write # Required to comment on the Pull Request
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ github.token }}
